export const AUTOCOMPLETE_MAX_SUGGESTIONS = 8;
export const AUTOCOMPLETE_MIN_QUERY_LENGTH = 2;
export const AUTOCOMPLETE_MAX_QUERY_LENGTH = 128;
export const SEARCH_QUERY_MAX_LENGTH = 512;
export const SEARCH_CURSOR_MAX_LENGTH = 4096;
export const SEARCH_MAX_PAGE = 12;
