use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - ddg definitions
      - brave
      - google
      - bing
      - startpage
      - duckduckgo images
      - brave.images
      - google images
      - bing images
      - startpage images
      - youtube
      - google videos
      - google news
      # Video alternates:
      # - bing videos
      # - brave.videos
      # - dailymotion
      # - duckduckgo videos
      # - odysee
      - startpage news
      - wikinews
      - bing news
      - brave.news
      - duckduckgo news
      - reuters
      - yahoo news

search:
  autocomplete: google
  autocomplete_min: 2
  # Alternate supported autocomplete backends:
  # autocomplete: brave
  # autocomplete: duckduckgo
  # autocomplete: bing
  formats:
    - html
    - json

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true

  searx.plugins.hash_plugin.SXNGPlugin:
    active: true

  searx.plugins.self_info.SXNGPlugin:
    active: true

  searx.plugins.unit_converter.SXNGPlugin:
    active: true

  searx.plugins.time_zone.SXNGPlugin:
    active: true

server:
  secret_key: "change-this-in-production"
  public_instance: false
  limiter: false
  image_proxy: false

engines:
  - name: duckduckgo
    disabled: false
  - name: ddg definitions
    disabled: false
  - name: brave
    disabled: false
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: startpage
    disabled: false
  - name: duckduckgo images
    disabled: false
  - name: brave.images
    disabled: false
  - name: google images
    disabled: false
  - name: bing images
    disabled: false
  - name: startpage images
    disabled: false
  - name: youtube
    disabled: false
  - name: google videos
    disabled: false
  - name: google news
    disabled: false
  # Video alternates:
  # - name: bing videos
  #   disabled: false
  # - name: brave.videos
  #   disabled: false
  # - name: dailymotion
  #   disabled: false
  # - name: duckduckgo videos
  #   disabled: false
  # - name: odysee
  #   disabled: false
  - name: startpage news
    disabled: false
  - name: wikinews
    disabled: false
  - name: bing news
    disabled: false
  - name: brave.news
    disabled: false
  - name: duckduckgo news
    disabled: false
  - name: reuters
    disabled: false
  - name: yahoo news
    disabled: false
